name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      with:
        version: latest

    - name: Bundle
      run: |
        pnpm install --frozen-lockfile
        pnpm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
