name: Update packages

on:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.2.0
      with:
        version: latest

    - name: Update and test
      run: |
        pnpm up
        pnpm i
        pnpm test
        pnpm run lint

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "ncu -u" -a --allow-empty

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
